version: "2"
linters:
  enable:
    - gocritic
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
        - rangeValCopy

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    paths:
      - "pkg/gen/*.go"
