before:
  hooks:
    - go mod tidy
builds:
  - binary: coolify
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/coollabsio/cli-coolify/cmd/config.Version={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - formats: ['tar.gz']
    name_template: >-
      coolify_{{ .Version }}_
      {{- .Os }}_{{ .Arch }}
checksum:
  name_template: 'coolify_{{ .Version }}_checksums.txt'
release:
  prerelease: auto
  make_latest: "{{ not .Prerelease }}"