version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: coolify
    binary: coolify
    main: ./coolify
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0