version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: coolify
    binary: coolify
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    main: ./coolify/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0