package services

import (
	"crypto/sha256"
	"encoding/hex"
	"net"
	"strings"
	"testing"
)

func TestCorrosionConfigBytes_GoldenThreeHost(t *testing.T) {
	self := net.ParseIP("100.64.0.1")
	peers := []net.IP{
		net.ParseIP("100.64.0.3"),
		net.ParseIP("100.64.0.2"), // intentionally unsorted
	}

	got := CorrosionConfigBytes(self, 8787, 8080, peers)

	want := `# generated by coolify init — do not edit
[db]
path = "/var/lib/corrosion/corrosion.db"
schema_paths = ["/etc/corrosion/schemas"]

[gossip]
addr = "100.64.0.1:8787"
bootstrap = ["100.64.0.2:8787", "100.64.0.3:8787"]
plaintext = true

[api]
addr = "127.0.0.1:8080"

[admin]
path = "/var/run/corrosion/admin.sock"
`
	if string(got) != want {
		t.Fatalf("config mismatch.\nWANT:\n%s\nGOT:\n%s", want, got)
	}
}

func TestCorrosionConfigBytes_StableHashAcrossOrderings(t *testing.T) {
	self := net.ParseIP("100.64.0.1")
	peersA := []net.IP{net.ParseIP("100.64.0.2"), net.ParseIP("100.64.0.3")}
	peersB := []net.IP{net.ParseIP("100.64.0.3"), net.ParseIP("100.64.0.2")}

	a := CorrosionConfigBytes(self, 8787, 8080, peersA)
	b := CorrosionConfigBytes(self, 8787, 8080, peersB)

	hashA := sha256.Sum256(a)
	hashB := sha256.Sum256(b)
	if hex.EncodeToString(hashA[:]) != hex.EncodeToString(hashB[:]) {
		t.Fatalf("hashes differ across peer orderings (sort broken):\nA=%x\nB=%x", hashA, hashB)
	}
}

func TestCorrosionConfigBytes_EmptyPeers(t *testing.T) {
	got := string(CorrosionConfigBytes(net.ParseIP("100.64.0.1"), 8787, 8080, nil))
	if !strings.Contains(got, `bootstrap = []`) {
		t.Fatalf("expected empty bootstrap array, got:\n%s", got)
	}
}

func TestCorrosionServiceUnit_ContainsInterface(t *testing.T) {
	got := CorrosionServiceUnit("wg0")
	for _, want := range []string{
		"After=network-online.target wg-quick@wg0.service",
		"Requires=wg-quick@wg0.service",
		"ExecStart=/usr/local/bin/corrosion agent --config /etc/corrosion/config.toml",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("unit missing %q:\n%s", want, got)
		}
	}
}
