// Package services generates configuration for the v5 control-plane
// daemons installed by `coolify init` (corrosion + coold).  All functions
// are pure: they emit bytes/strings and do no I/O.
package services

import (
	"fmt"
	"net"
	"sort"
	"strings"
)

// CoolifySchemaSQL is the Corrosion schema that coold's sync loop writes to.
//
// Every NOT NULL column MUST have a DEFAULT — corrosion's CR-SQLite backend
// rejects schemas missing defaults with "needs a default value for forward
// schema compatibility".  Defaults are never surfaced at runtime because
// coold always provides every column on upsert.
const CoolifySchemaSQL = `CREATE TABLE service_endpoints (
    container_id    TEXT NOT NULL DEFAULT '' PRIMARY KEY,
    container_name  TEXT NOT NULL DEFAULT '',
    host_mgmt_ip    TEXT NOT NULL DEFAULT '',
    container_ip    TEXT NOT NULL DEFAULT '',
    healthy         INTEGER NOT NULL DEFAULT 1,
    updated_at      INTEGER NOT NULL DEFAULT 0
);
`

// CorrosionConfigBytes renders /etc/corrosion/config.toml for a single host.
//
// bindAddr is this host's wg0 management IP — gossip is confined to the mesh
// (already encrypted by WireGuard, so plaintext=true is safe).
// peers are the mgmt IPs of all OTHER hosts; they are sorted lexically so the
// output is byte-stable across probe orderings (needed for sha256 drift check).
func CorrosionConfigBytes(bindAddr net.IP, gossipPort, apiPort int, peers []net.IP) []byte {
	sorted := make([]string, 0, len(peers))
	for _, p := range peers {
		if p == nil {
			continue
		}
		sorted = append(sorted, p.String())
	}
	sort.Strings(sorted)

	var b strings.Builder
	b.WriteString("# generated by coolify init — do not edit\n")
	b.WriteString("[db]\n")
	b.WriteString(`path = "/var/lib/corrosion/corrosion.db"` + "\n")
	b.WriteString(`schema_paths = ["/etc/corrosion/schemas"]` + "\n")
	b.WriteString("\n[gossip]\n")
	fmt.Fprintf(&b, "addr = \"%s:%d\"\n", bindAddr, gossipPort)
	b.WriteString("bootstrap = [")
	for i, p := range sorted {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "\"%s:%d\"", p, gossipPort)
	}
	b.WriteString("]\n")
	b.WriteString("plaintext = true\n")
	b.WriteString("\n[api]\n")
	fmt.Fprintf(&b, "addr = \"127.0.0.1:%d\"\n", apiPort)
	b.WriteString("\n[admin]\n")
	b.WriteString(`path = "/var/run/corrosion/admin.sock"` + "\n")
	return []byte(b.String())
}

// CorrosionServiceUnit returns the systemd unit text for corrosion.
// Plain .service (not a template unit); iface is baked into the dependency.
func CorrosionServiceUnit(iface string) string {
	return fmt.Sprintf(`[Unit]
Description=Corrosion agent
After=network-online.target wg-quick@%[1]s.service
Wants=network-online.target
Requires=wg-quick@%[1]s.service

[Service]
ExecStart=/usr/local/bin/corrosion agent --config /etc/corrosion/config.toml
Restart=on-failure
RestartSec=2s
StateDirectory=corrosion
WorkingDirectory=/var/lib/corrosion

[Install]
WantedBy=multi-user.target
`, iface)
}
