package services

import (
	"crypto/sha256"
	"encoding/hex"
	"net"
	"strings"
	"testing"
)

func TestCorrosionInstallCommand_SubstitutesVersion(t *testing.T) {
	for _, version := range []string{"nightly", "v1.2.3"} {
		cmd := CorrosionInstallCommand(version)
		if !strings.Contains(cmd, version) {
			t.Errorf("version %q not found in install command", version)
		}
		if !strings.Contains(cmd, "coollabsio/corrosion/releases/download/"+version) {
			t.Errorf("release URL missing version %q in:\n%s", version, cmd)
		}
		if !strings.Contains(cmd, "/usr/local/bin/corrosion.version") {
			t.Errorf("version marker write missing from install command")
		}
	}
}

func TestCorrosionInstallCommand_ArchDetection(t *testing.T) {
	cmd := CorrosionInstallCommand("nightly")
	for _, want := range []string{
		"x86_64)  ARCH=x86_64-unknown-linux-gnu",
		"aarch64) ARCH=aarch64-unknown-linux-gnu",
		"corrosion-${ARCH}.tar.gz",
		"install -m 0755",
	} {
		if !strings.Contains(cmd, want) {
			t.Errorf("expected %q in install command:\n%s", want, cmd)
		}
	}
}

func TestCorrosionConfigBytes_GoldenThreeHost(t *testing.T) {
	self := net.ParseIP("100.64.0.1")
	peers := []net.IP{
		net.ParseIP("100.64.0.3"),
		net.ParseIP("100.64.0.2"), // intentionally unsorted
	}

	got := CorrosionConfigBytes(self, 8787, 8080, peers)

	want := `# generated by coolify init — do not edit
[db]
path = "/var/lib/corrosion/corrosion.db"
schema_paths = ["/etc/corrosion/schemas"]

[gossip]
addr = "100.64.0.1:8787"
bootstrap = ["100.64.0.2:8787", "100.64.0.3:8787"]
plaintext = true

[api]
addr = "127.0.0.1:8080"

[admin]
path = "/var/run/corrosion/admin.sock"
`
	if string(got) != want {
		t.Fatalf("config mismatch.\nWANT:\n%s\nGOT:\n%s", want, got)
	}
}

func TestCorrosionConfigBytes_StableHashAcrossOrderings(t *testing.T) {
	self := net.ParseIP("100.64.0.1")
	peersA := []net.IP{net.ParseIP("100.64.0.2"), net.ParseIP("100.64.0.3")}
	peersB := []net.IP{net.ParseIP("100.64.0.3"), net.ParseIP("100.64.0.2")}

	a := CorrosionConfigBytes(self, 8787, 8080, peersA)
	b := CorrosionConfigBytes(self, 8787, 8080, peersB)

	hashA := sha256.Sum256(a)
	hashB := sha256.Sum256(b)
	if hex.EncodeToString(hashA[:]) != hex.EncodeToString(hashB[:]) {
		t.Fatalf("hashes differ across peer orderings (sort broken):\nA=%x\nB=%x", hashA, hashB)
	}
}

func TestCorrosionConfigBytes_EmptyPeers(t *testing.T) {
	got := string(CorrosionConfigBytes(net.ParseIP("100.64.0.1"), 8787, 8080, nil))
	if !strings.Contains(got, `bootstrap = []`) {
		t.Fatalf("expected empty bootstrap array, got:\n%s", got)
	}
}

func TestCoolifySchema_HasLivenessAndReadinessColumns(t *testing.T) {
	for _, want := range []string{
		"state           TEXT NOT NULL DEFAULT ''",
		"health          TEXT NOT NULL DEFAULT 'unknown'",
	} {
		if !strings.Contains(CoolifySchemaSQL, want) {
			t.Errorf("schema missing %q:\n%s", want, CoolifySchemaSQL)
		}
	}
	if strings.Contains(CoolifySchemaSQL, "healthy") {
		t.Errorf("schema still has removed `healthy` column:\n%s", CoolifySchemaSQL)
	}
}

func TestCoolifySchema_HasContainerNameColumn(t *testing.T) {
	// container_name is the DNS label coold's resolver queries on. Flat
	// scheme: <container_name>.coolify.internal → container_ip. Coolify
	// enforces global uniqueness.
	want := "container_name  TEXT NOT NULL DEFAULT ''"
	if !strings.Contains(CoolifySchemaSQL, want) {
		t.Errorf("schema missing %q:\n%s", want, CoolifySchemaSQL)
	}
}

func TestCoolifySchema_HasNamespaceColumn(t *testing.T) {
	// namespace is reserved for future per-app isolation / multi-tenant.
	// Empty in single-tenant; populated when Coolify wants app scoping.
	want := "namespace       TEXT NOT NULL DEFAULT ''"
	if !strings.Contains(CoolifySchemaSQL, want) {
		t.Errorf("schema missing %q:\n%s", want, CoolifySchemaSQL)
	}
}

func TestCoolifySchema_AllNotNullColumnsHaveDefault(t *testing.T) {
	// CR-SQLite rejects any NOT NULL column missing a DEFAULT with
	// "needs a default value for forward schema compatibility".
	for _, line := range strings.Split(CoolifySchemaSQL, "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.Contains(trimmed, "NOT NULL") {
			continue
		}
		if !strings.Contains(trimmed, "DEFAULT") {
			t.Errorf("line missing DEFAULT (CR-SQLite would reject): %q", trimmed)
		}
	}
}

func TestCorrosionServiceUnit_ContainsInterface(t *testing.T) {
	got := CorrosionServiceUnit("wg0")
	for _, want := range []string{
		"After=network-online.target wg-quick@wg0.service",
		"Requires=wg-quick@wg0.service",
		"ExecStart=/usr/local/bin/corrosion agent --config /etc/corrosion/config.toml",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("unit missing %q:\n%s", want, got)
		}
	}
}
